# Load libraries
library(shiny)
library(shinythemes)
library(tidyverse)
library(randomForest)
library(caret)

# In this shiny demo app, we will be using the ANES pilot survey data - that Pete used in his ML tutorial. Credits to Pete!
# Data Loading and Pre-processing (straight from Pete's ML tutorial)
data <- read_csv("data/anes_pilot_2020ets_csv.csv")
data_clean <- data %>%
  select(viol2a, fttrump1:ftdemocraticparty, econnow:ineqinc1a) # select relevant variables
data_clean[data_clean == 999] <- NA #replace "999" ("I don't know" responses) with NAs
data_clean <- data_clean %>%
  na.omit() %>% #remove rows with NAs
  mutate(violence_ok = as.factor(if_else(viol2a == 1, 0, 1))) %>% #convert original variable to binary response, as described above
  select(-viol2a, -billtax2, -guarinc2, -freemkt2, -freemkt3, -govsize2, -govsize3, -regulate2) #drop some columns

# Define UI
ui <- fluidPage(navbarPage("QWG Shiny Demo App 2: ANES Pilot Survey", # App title displayed at the navigation bar #theme = shinytheme("paper"),
                           tabPanel("Interactive Histogram",
                                    sidebarLayout( # specify the layout of your page
                                      sidebarPanel( # specify inputs
                                        # Creates a select list to choose a single variable from the dataset
                                        selectInput("select_var", label="Select the variable to plot:",
                                                                  choices = names(data_clean),
                                                                  selected= "ftbiden1"),
                                        # Creates a slider to select a numeric value for the number of bins:
                                        sliderInput(inputId = "bins",label = "Select number of bins:",
                                                    min = 1, max = 20, value = 10),
                                        # Creates a select list to choose a color to fill the bins of the histogram:
                                        selectInput("bins_color","Select color to fill the bins:",
                                                    choices = c("blue", "red", "darkgreen", "orange")),
                                        # Creates a checkbox to speficy a logical value on whether to include a line represnting the mean:
                                        checkboxInput("includemeanline", "Include mean line",
                                                      value = FALSE),
                                        # Creates an input control for entry of text to be used for histogram title:
                                        textInput("hist_title", label = "Enter plot title"),
                                        # Creates an input control for entry of text to be used for x-axis label:
                                        textInput( "x_label", label = "X-axis label")
                                        ), # close sidebarPanel
                                      mainPanel( # display the output generated by server using inputs from ui
                                        tabsetPanel( # Create a tabset that contains tabPanel() elements. 
                                          tabPanel(title = "Histogram",
                                                   # Using plotOutput to render the distPlot (from server):
                                                   plotOutput("distPlot")),
                                          tabPanel(title = "Summary",
                                                   # Using verbatimTextOutput to produce a text box in order display output value for summary (from server):
                                                   verbatimTextOutput("summary"))
                                          ) # close tabsetPanel
                                        ) # close mainPanel
                                      ) # close sidebarLayout
                                    ), # close tabPanel
                           tabPanel("ML: Logit versus Random Forest",
                                    sidebarLayout(
                                      sidebarPanel(
                                        sliderInput("trainingsize", label = "Select percentage of data to keep for training:",
                                                    min = 70, max = 90,
                                                    value = 80),
                                        selectInput("modeltype", label = "Select the type of learner:",
                                                    choices = c("Logit", "Random Forest"),
                                                    selected = "Logit"),
                                        actionButton("submitbutton", "Submit", class = "btn btn-primary")
                                        ), # close sidebarPanel
                                      mainPanel(
                                        tags$label(h3('Status/Output')), 
                                        verbatimTextOutput('status'), # Status/Output Text Box
                                        verbatimTextOutput('result'), # Result for test set accuracy
                                        # Using html tags to embed a link (where a tag defines a hyperlink):
                                        tags$a(href = "https://github.com/pcuppernull/supervised-ml-tutorial", 
                                               "Source: Pete Cuppernull's GitHub Repository", target = "_blank")
                                        ) # close mainPanel
                                      ) # close sidebarLayout
                                    ) # close tabPabel
                           ) # close navbarPage
                ) # close fluidPage


# Define server
server <- function(input, output, session) {
  
  # Generating histogram for the selected input variable (with inputs specified within the ui):
  output$distPlot <- renderPlot({
    # Subsetting the data to selected variable and checking whether or not the selected variable is factor:
    if (is.factor(data_clean[[input$select_var]])){
      # if so we need to use the method below to get to the values (rather than get the level values printed):
      x    <- as.numeric(levels(data_clean[[input$select_var]]))
    } else {
      x    <- as.numeric(data_clean[[input$select_var]])
    }
    # Generating bins based on input$bins we have from ui
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    # Drawing the histogram of selected variable, with the specified number of bins and color:
    hist(x, 
         # Specifying breakpoints with bins we created above using input$bins from ui
         breaks = bins, 
         # Specifying coloring of the bins using input$bins_color from ui
         col = input$bins_color,
         # Specifying title of the histogram using input$hist_title from ui
         main = input$hist_title,
         # Specifying x axis label of the histogram using input$x_label from ui
         xlab = input$x_label,
         border = 'white')
    
    # Adding a vertical line at the mean if the includemeanline checkbox from ui is checked
    if(input$includemeanline) { # checking if the box is checked or not
      # Add a vertical line at the mean of x
      abline(v = mean(x),
             lwd = 3, # thickness of the line
             lty = 2) # make line type dashed 
    }
  })
  
  
  # Generating summary statistics for the selected input variable:
  output$summary <- renderPrint({
    # Function to return summary statistics:
    summary(data_clean[[input$select_var]])
  })
  
  
  # Running learners (type specified in ui) for predicting violence_ok:
  runmodel <- reactive({ # wrapping it with reactive:
    # Split data into training/test set:
    set.seed(1414) # set seed
    # Choose rows from data_clean to sample by keeping x% of the data in training: x--input$trainingsize
    sample <- sample(nrow(data_clean), nrow(data_clean)*(input$trainingsize/100)) 
    training <- data_clean[sample,] # save those rows as training
    testing <- data_clean[-sample,] # add all the other rows to testing
    
    # Running logit if user inputs Logit as the learner type:
    if (input$modeltype == "Logit"){
      # Build Logit model
      fitControl <- trainControl(method = "cv", number = 10)
      logit_fit <- train(violence_ok ~ ., #regress violence_ok onto all other predictors, which is what the "." means
                       method = "glm",
                       family = "binomial",  #method and family here specify a logit model
                       data = training, #using our training data
                       trControl = fitControl) #add our macro parameters
      
      # Calculate accuracy on test set:
      accuracy_test <- (1 - sum(abs((as.numeric(predict(logit_fit, testing)) - 1) - (as.numeric(testing$violence_ok) - 1))) / nrow(testing))
    }
    
    # Running random forest if user inputs Random Forest as the learner type:
    if (input$modeltype == "Random Forest"){
      # Build Random Forest model
      rf_classifier = randomForest(violence_ok ~ ., data=training, ntree=100, mtry=6, importance=TRUE)
      
      # Calculate accuracy on test set:
      accuracy_test <- (1 - sum(abs((as.numeric(predict(rf_classifier, testing)) - 1) - (as.numeric(testing$violence_ok) - 1))) / nrow(testing))
    }
    
    # Print the result:
    print(paste("Test Accuracy:", accuracy_test))
    
  })
  
  
  # Status Text Box
  output$status <- renderPrint({
    # If the user hits submit button, display:
    if (input$submitbutton>0) { 
      isolate("Calculation is complete.") 
    } else {
      return("Server is ready for calculation.")
    }
  })
  
  # Output Text Box
  output$result <- renderPrint({
    # If the user hits submit button, display the result of the runmodel function:
    if (input$submitbutton>0) { 
      isolate(runmodel()) 
    } else {
      # Else, before submission, display:
      return("Accuracy (on test set):")
    }
  })
  
  
} # close server 

shinyApp(ui = ui, server = server)
